# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
#    mac:
#      imageName: 'macOS-latest'
#    windows:
#      imageName: 'windows-latest'

trigger:
  - master

pool:
  vmImage: $(imageName)

steps:
  - script: |
      python3 -m pip install -r requirements.txt
      python3 -m pip install -r requirements-test.txt
      tox
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/dist'
      ArtifactName: 'compute-$(imageName)'
      publishLocation: 'Container'