# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

resources:
    containers:
    - container: manylinux1
      image: dockcross:manylinux-x64

pool:
  vmImage: ubuntu-latets
  container: manylinux1

stages:
  - stage: Tox
    displayName: 'Tox Execution'
    jobs:
      - job: ToxExecution
        steps:
          - script: |
              python3 -V
              python3 -m pip install -r requirements.txt
              tox
              cd dist
              ls

