# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

stages:
  - stage: MacBuild
    displayName: 'MacBuild'
    pool:
      vmImage: macOS-10.14
    jobs:
      - job: ToxExecution
        steps:
          - task: Cache@2
            inputs:
              key: 'DownloadArtifacts'
              path: '$(System.DefaultWorkingDirectory)/.downloads'
          - task: Cache@2
            inputs:
              key: 'MacExternalArtifacts'
              path: '$(System.DefaultWorkingDirectory)/external'
          - script: |
              python3 -V
              python3 -m pip install -r requirements.txt
              tox
              cd dist
              ls

