# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

resources:
    containers:
    - container: manylinux1
      image: dockcross/manylinux2014-aarch64

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Tox
    displayName: 'Tox Execution'
    jobs:
      - job: ToxExecution
        container: manylinux1
        steps:
          - script: |
              printenv
              pip install -r requirements.txt
              tox
              cd dist
              ls

