# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: macOS-10.14

stages:
  - stage: Setup
    
  - stage: Tox
    displayName: 'Tox Execution'
    jobs:
      - job: ToxExecution
        steps:
          - task: Cache@2
            inputs:
              key: 'DownloadArtifacts'
              path: '$(System.DefaultWorkingDirectory)/.downloads'
          - script: |
              python3 -V
              python3 -m pip install -r requirements.txt
              tox
              cd dist
              ls

